import type { Article } from './articles';
export const blockedDrainsGuide: Article = {
 title:'Why Drains Keep Blocking',slug:'why-drains-keep-blocking',metaTitle:'Why Drains Keep Blocking: Causes & Next Steps | Grade A Plumbing',metaDescription:'Recurring blocked drains need more than another quick clearance. Learn what to record, how inspection helps and which repair questions to ask in Melbourne.',author:'Grade A Plumbing',publishedDate:'2026-09-20',updatedDate:'2026-10-01',status:'published',locationSlugs:['melbourne'],excerpt:'A drain that blocks again needs a clearer explanation of the cause. Understand recurring symptoms, inspection options and practical ways to reduce preventable blockages.',relatedServices:['blocked-drains','sewer-repairs','pipe-relining'],relatedArticles:['sewer-repair-vs-pipe-relining','before-booking-a-plumber-in-coburg-photos-access-and-questions-to-prepare'],
 sources:[{title:'South East Water: blockage symptoms, responsibilities and prevention',url:'https://southeastwater.com.au/faults-and-works/maintenance/blockages/'},{title:'Building and Plumbing Commission: choosing a plumbing practitioner',url:'https://www.bpc.vic.gov.au/home-owners/before-you-start-building/engaging-a-plumber'}],
 faq:[{question:'Does another blockage prove the last plumber did a bad job?',answer:'No. Clearance can restore flow without resolving a separate pipe condition. Compare the original scope, findings and current symptoms before deciding what happened.'},{question:'Are wipes labelled flushable safe for the sewer?',answer:'South East Water advises keeping all wipes out of the sewer, including products labelled flushable. Put them in the appropriate bin.'},{question:'Can a camera inspect a completely blocked pipe?',answer:'Access and visibility can be limited by the obstruction and conditions. Ask whether clearing or preparation is needed before useful footage can be obtained.'},{question:'Who pays if the fault is in a public sewer?',answer:'The location and water retailer’s current rules matter. Confirm ownership and reporting requirements before authorising repair. Do not assume every Melbourne property has the same retailer.'}],
 sections:[
 {heading:'Why a drain can flow today and block again later',paragraphs:[
 'Clearing a blockage and correcting its underlying cause are not always the same job. The immediate visit may restore flow, while a condition elsewhere in the drain remains unresolved. A return of symptoms therefore deserves investigation, not an automatic assumption that the pipe needs replacement or that the previous service was ineffective. Start by reviewing what was found and what work was actually authorised.',
 'The most useful question is why this particular drain is struggling repeatedly. A recurring obstruction, an unresolved pipe fault and ongoing material entering the system lead to different decisions. You do not need to diagnose the cause before contacting a plumber. Explain the pattern, provide previous reports if available and ask which investigation would help distinguish the options.',
 'For Melbourne properties, avoid assigning a cause purely from the suburb or the age of the house. A mature garden does not prove root intrusion, and recent renovation does not prove sound drainage. This guide focuses on what you can observe and the questions to ask. The separate repair-versus-relining guide considers repair selection after a fault has been identified, rather than repeating the same search intent.'
 ]},
 {heading:'Record the pattern before the next visit',paragraphs:[
 'Write down which fixtures are affected and whether they react at the same time. Note slow emptying, unusual sounds, unpleasant smells and visible wastewater. Explain whether the issue appears after a washing machine cycle, during normal bathroom use or without an obvious trigger. These are observations to help the assessment, not instructions to run more water to reproduce a potentially damaging overflow.',
 'Keep a timeline of earlier clearance visits, how long the improvement lasted and whether the current symptoms match the earlier ones. If you have a report, ask for the location identified, the condition described and any recommended follow-up. A short statement that a drain was cleared does not necessarily tell you whether its full length was inspected or whether structural issues were ruled out.',
 'Photograph accessible fixtures and outdoor areas from a safe position. A wide shot can show access restrictions that a close-up misses. Do not lift heavy covers, enter pits or approach sewage for a photograph. Tell the booking team about any chemicals or attempted repairs, even if they did not work, so the attending professional understands what may be present in the drain.'
 ]},
 {heading:'Distinguish a local fixture problem from a wider drainage issue',paragraphs:[
 'One slow outlet and several affected fixtures are different starting points for an investigation. Ask whether the assessment will consider the immediate fixture, the connected branch and any relevant downstream pipework. The visible symptom alone cannot establish how far the problem extends. A professional may need to inspect more than the room where the issue first became noticeable.',
 'Clarify whether the affected system carries wastewater or stormwater. Give the plumber your actual observations rather than calling every outdoor grate a sewer access point. If symptoms follow rainfall, mention the timing without concluding that rain is the cause. Avoid connecting or redirecting pipework yourself in an attempt to solve the problem; ownership, function and compliance need to be understood first.',
 'For units, shared buildings and businesses, identify who can arrange access to relevant areas. A pipe serving several properties may need different approval arrangements from a private branch. Contact building management or the appropriate property representative where necessary. Ask for the ownership position to be clarified before authorising work that could affect other occupants or an asset belonging to a water retailer.'
 ]},
 {heading:'Possible contributors and why evidence matters',paragraphs:[
 'South East Water identifies tree roots and unsuitable material entering the sewer as contributors to blockages. Its prevention advice includes keeping fats, food scraps, wipes and sanitary items out of the sewer. These are practical risks to consider, but they are not proof of the cause at your address. Ask for inspection findings that connect the recommendation to your particular problem.',
 'If a report describes damaged pipework or a recurring obstruction, ask where it was found and how confidently it was identified. Can the attending professional show you the relevant footage or photographs? What remains uncertain? A clear explanation should separate observed conditions from possibilities. It should also explain whether further inspection is needed before choosing a permanent repair.',
 'Do not assume the whole drain needs replacement because one section has a fault. Equally, do not assume another clearance will provide a lasting answer simply because it restored flow last time. Ask whether the proposed work addresses the identified issue, which sections remain outside the scope and whether there is a reason to inspect those sections before committing to a larger project.'
 ]},
 {heading:'What to ask about camera inspection and clearance',paragraphs:[
 'A camera inspection can help document an accessible section of pipe, but its usefulness depends on visibility, access and the condition encountered. Ask whether the drain first needs preparation or clearance, what length is expected to be inspected and whether you will receive usable findings. A camera visit is not a promise that every hidden issue can be ruled out in every circumstance.',
 'Ask the plumber to explain the aim of any proposed clearance: restoring flow, preparing for inspection or carrying out planned maintenance. Clarify what is included in the visit and whether additional investigation would require separate approval. Avoid comparing quotes solely by the name of a machine or a short headline price; compare the actual service scope and the information you receive afterwards.',
 'Where a repair is recommended, request a description of the fault, its location and the proposed solution. Ask what makes the option suitable and what alternatives were considered. You may be comparing targeted repair, replacement or relining, but suitability should follow the findings. Use the related repair guide for those questions rather than treating any one method as the default answer to repeat blockages.'
 ]},
 {heading:'Reduce preventable problems without attempting risky repairs',paragraphs:[
 'Keep inappropriate waste out of sinks and toilets, following your water retailer’s disposal advice. Routine household habits are different from working on drainage infrastructure. If a problem continues despite sensible disposal practices, arrange assessment rather than repeatedly adding products or relying on an unsupported claim that a chemical will fix every obstruction.',
 'When wastewater is backing up, stop using affected fixtures and limit activities that add water to the system while seeking advice. Keep people and pets away from contaminated areas. South East Water recommends limiting water use while a blockage is being fixed. For an active overflow, call rather than waiting for an email response; obtain emergency assistance if there is immediate danger.',
 'Responsibility depends on where the fault sits and which retailer serves the property. South East Water’s published guidance applies to its network, not automatically to every Melbourne address. If you rent, report the issue through the property’s repair process and keep records. Confirm the relevant retailer and reporting arrangements where public infrastructure may be involved before agreeing to work on it.'
 ]},
 {heading:'Book a focused assessment for recurring blocked drains',paragraphs:[
 'Prepare the address, affected fixtures, recurrence timeline, earlier reports and access details. Ask what the assessment will cover and how additional work is approved. After the visit, request a clear summary distinguishing the immediate clearance from any proposed follow-up. Keep records so the next decision builds on evidence instead of starting from the same incomplete description.',
 'Contact Grade A Plumbing on (02) 5837 5457 or email support@gradeaplumbing.store with your suburb and symptoms. Explain if there is an active overflow so urgency can be discussed. We can discuss current service availability and an appropriate next step; neither a photograph nor this guide guarantees a diagnosis, price or arrival time for your property.'
 ]}
 ]
};
