import type { Article } from './articles';
const sectionOrder = ["Start with the problem you can see","Explain urgency before collecting photos","Take photos that show both the fault and access","Write a short timeline of the symptoms","Arrange access before the appointment","For rentals and shared buildings, identify the decision-maker","Ask what the quote and assessment cover","Discuss the right next step for the service you need","Keep a simple booking checklist","Request plumbing help in Coburg"];
export const coburgBookingArticle: Article = {
  "title": "Before Booking a Plumber in Coburg: Photos, Access and Questions to Prepare",
  "slug": "before-booking-a-plumber-in-coburg-photos-access-and-questions-to-prepare",
  "metaTitle": "Booking a Plumber in Coburg: Preparation Guide | Grade A Plumbing",
  "metaDescription": "Prepare for a plumber visit in Coburg with a practical guide to photos, symptoms, access, quotes and questions before plumbing work starts.",
  "author": "Grade A Plumbing",
  "publishedDate": "2026-10-01",
  "updatedDate": "2026-10-01",
  "sources": [
    {"title":"Building and Plumbing Commission: engaging a plumber","url":"https://www.bpc.vic.gov.au/home-owners/before-you-start-building/engaging-a-plumber"},
    {"title":"Plumbing compliance certificates","url":"https://www.vba.vic.gov.au/plumbing/renewals-other-requirements/compliance-certificates"},
    {"title":"Consumer Affairs Victoria: rental repairs","url":"https://www.consumer.vic.gov.au/housing/renting/repairs-alterations-safety-and-pets/repairs"}
  ],
  "excerpt": "A clear description, useful photos and straightforward access arrangements help a plumber understand your problem. Here is how to prepare for a service visit in Coburg and nearby suburbs.",
  "relatedServices": [
    "blocked-drains",
    "hot-water",
    "emergency-plumber"
  ],
  "relatedArticles": [
    "why-drains-keep-blocking",
    "how-long-does-a-hot-water-system-last"
  ],
  "locationSlugs": [
    "coburg"
  ],
  "status": "published",
  "faq": [
    {
      "question": "Can a plumber diagnose a problem from photographs?",
      "answer": "Photos help explain symptoms and access, but they do not replace inspection. Hidden pipework, intermittent faults and drainage problems may need testing before the cause and repair can be confirmed."
    },
    {
      "question": "What if I do not know where the water meter is?",
      "answer": "Tell the booking team. Do not force a valve or enter an unsafe area to find it. The plumber can discuss access and appropriate isolation during the visit."
    },
    {
      "question": "Do you also take enquiries from suburbs near Coburg?",
      "answer": "Contact Grade A Plumbing with your address and plumbing issue to confirm availability for Coburg North, Brunswick, Pascoe Vale, Preston, Fawkner or another nearby suburb."
    },
    {
      "question": "Should I clear a drain before a plumber arrives?",
      "answer": "You do not need to attempt repairs before booking. Report any products or tools already used and avoid adding chemicals or dismantling plumbing while waiting for professional advice."
    }
  ],
  "sections": [
    {
      "heading": "Start with the problem you can see",
      "paragraphs": [
        "Booking a plumber in Coburg is easier when your first message explains what is happening rather than guessing which part needs replacement. A dripping kitchen mixer, water beneath a vanity and a toilet that keeps refilling are different starting points. Describe the symptom, the room and when you first noticed it. If the problem comes and goes, record the circumstances that make it appear.",
        "For example, explain whether a leak occurs continuously, only when a tap runs, or after a washing machine drains. Note whether one fixture is affected or several. These observations can help the booking team understand the type of enquiry and what access may be required. They are clues for assessment, not proof of a particular diagnosis.",
        "Give your full property address, including the unit number, and say whether the property is in Coburg itself or a nearby suburb such as Coburg North, Brunswick, Pascoe Vale or Preston. Service timing depends on the address, the nature of the fault and current bookings. Ask for the available appointment window rather than assuming a published service area guarantees immediate attendance."
      ]
    },
    {
      "heading": "Explain urgency before collecting photos",
      "paragraphs": [
        "If water is escaping rapidly, a toilet is overflowing or a leak threatens an occupied area, call first. Do not delay the initial contact while trying to produce a perfect set of photographs. Explain whether water is still flowing, whether anyone is at the property and whether the affected area can be kept clear.",
        "Keep away from water near electrical equipment and from areas with sewage contamination. Do not remove covers, enter a roof space, climb onto a roof or approach damaged electrical fittings to investigate. If there is immediate danger, contact emergency services. Plumbing work and electrical safety may require different qualified professionals.",
        "For a routine drip or a slow drain without an overflow, a written enquiry may be appropriate. Include the symptoms and a preferred contact time so the team can discuss the next step. An emergency assessment and a planned maintenance visit may involve different arrangements; clarify those arrangements during booking."
      ]
    }
  ]
};
coburgBookingArticle.sections.push(...[{"heading":"Keep a simple booking checklist","paragraphs":["Before you call, have five things ready: the full address, your callback number, a short symptom description, when the issue started and any access restrictions. If the fault is routine, add a few clear photographs and your preferred appointment times. If it is urgent, lead with the immediate problem and collect other information afterwards.","During the conversation, confirm the appointment window, assessment arrangements and who can approve the proposed work. Ask how the team will contact you on arrival and what happens if the inspection reveals a different scope. Write the agreed details down so everyone involved in the property has the same information.","After the visit, keep the invoice, report and any required certificate. Ask what was found, what was completed and whether further work or monitoring is recommended. A clear record helps if the symptom returns or another trade needs information. It also gives you a practical basis for future maintenance instead of relying on memory."]},{"heading":"Request plumbing help in Coburg","paragraphs":["For a Coburg plumbing enquiry, call Grade A Plumbing on (02) 5837 5457 or email support@gradeaplumbing.store with your address, symptoms and a safe, accessible photo if available. For an urgent issue, call first to discuss the available next step. Availability and the appropriate service scope need to be confirmed for your property.","Use the Coburg location page to explore the services relevant to your enquiry. If your property is in a nearby suburb, include that suburb in the request rather than assuming the address can be inferred. Good preparation helps the conversation start with the information needed to organise an assessment."]}]);
coburgBookingArticle.sections.push(...[{"heading":"Ask what the quote and assessment cover","paragraphs":["Before confirming attendance, ask about the assessment process, any applicable attendance or diagnostic charges, and how further work will be authorised. A symptom description does not always support a fixed repair price because the cause may be concealed. Ask what can be quoted in advance and what requires inspection.","When comparing options, compare the scope as well as the total. Check which work, materials, access provisions and follow-up checks are included, and ask how unexpected findings will be handled. A drain-clearing visit, a camera inspection and a permanent pipe repair are different services. Make sure the proposed work addresses your agreed objective.","For a larger job, request written details and retain the quote and acceptance. Ask who will perform the work and how to check their registration or licence for the relevant class of plumbing. Victoria's Building and Plumbing Commission publishes guidance on engaging a plumber and compliance certificates. Ask whether a certificate is required for your specific scope rather than treating every small maintenance task identically."]},{"heading":"Discuss the right next step for the service you need","paragraphs":["A blocked drain enquiry should describe which fixtures are affected, whether there is an overflow and whether the blockage has occurred before. The plumber may need to assess access and pipe condition before recommending clearing, inspection or repair. Clearing a blockage can restore flow without establishing that every section of the pipe is sound.","For hot water problems, explain whether there is no hot water, inconsistent temperature, visible leakage or another symptom. Say whether all outlets are affected and provide accessible system-label photos. Keep away from electrical or gas components and avoid attempting adjustments. Assessment should establish the fault before a repair or replacement decision.","For a tap, toilet or fixture change, provide photographs of the existing installation and details of any replacement product you already own. Compatibility, access and the condition of existing connections may affect the work. Ask whether supply and installation are both included and whether the old fixture will be removed from the property."]}]);
coburgBookingArticle.sections.push(...[{"heading":"Arrange access before the appointment","paragraphs":["Confirm who will let the plumber in and who can approve the work. Provide entry instructions through the agreed booking channel, including an intercom name or gate arrangement where relevant. Avoid publishing access codes in a public message. If nobody can remain on site, discuss that before confirming the visit.","Clear a reasonable path to the affected fixture and remove loose personal items from an accessible under-sink cupboard if it is safe. Do not shift a connected appliance, dismantle cabinets or lift heavy equipment yourself. Tell the team about pets, restricted passages, stairs and any parking or loading constraints that you already know.","Coburg enquiries may involve a detached home, a unit, a rental or a business. The actual property layout determines access requirements. Explain your situation instead of assuming the suburb alone tells the plumber what to expect. A tenant may need approval from a property manager; a unit may involve shared services; a shop may require work to be coordinated around customers."]},{"heading":"For rentals and shared buildings, identify the decision-maker","paragraphs":["If you rent, contact your rental provider or property manager using the repair process supplied for the property. Tell them the symptoms, when the problem began and whether water is actively escaping. Keep a record of your messages. Urgent repair procedures can depend on the circumstances, so use current Consumer Affairs Victoria guidance where needed.","In an apartment or managed building, ask whether the relevant pipework is private or shared and who can authorise access or shutdowns. Do not assume that a leak visible in your unit originates there. Building management may need to coordinate entry to another area or notify occupants before work proceeds.","For a commercial property, distinguish the person requesting service from the person approving expenditure. Give the business contact, operating hours and any site induction requirements. If a service interruption would affect staff or customers, discuss how it will be communicated. Clear authority and access arrangements help prevent an inspection from stalling while approvals are sought."]}]);
coburgBookingArticle.sections.push(...[{"heading":"Take photos that show both the fault and access","paragraphs":["A useful photo set starts with one wide view of the room or fixture, followed by a closer view of the visible problem. The wide view shows where the issue sits and whether nearby cabinets, appliances or walls may restrict access. A close-up can show a drip, staining, corrosion or a damaged connection without hiding the surrounding layout.","Photograph accessible labels on a hot water system if you can do so safely. The manufacturer, model and visible system type may help explain the enquiry. Do not open panels or move heavy equipment to expose a label. For an under-sink leak, photograph the accessible pipework from outside the cabinet rather than pulling fittings apart.","For drainage enquiries, a photo of the affected fixture or safely accessible outdoor drain may be useful. A short video can show intermittent symptoms such as a gurgle or a leak appearing when a fixture operates, but avoid recreating an overflow for the camera. Never include payment details, identity documents or unnecessary private information in a job photo."]},{"heading":"Write a short timeline of the symptoms","paragraphs":["Think about the last time the plumbing worked normally and what changed before the fault appeared. Was there recent fixture replacement, building work, an extended period without use or a previous blockage? Note these events without assuming that they caused the problem. A sequence of observations is more useful than a confident guess.","Mention earlier repair visits and keep any relevant invoices, inspection reports or camera findings available. If a drain has been cleared repeatedly, tell the plumber when that happened and how long it flowed normally afterwards. A previous repair may help guide inspection, but the current condition still needs assessment.","Also disclose any drain cleaner, temporary sealant or attempted repair. The person attending needs to know what they may encounter. If you cannot remember a product name, keep its packaging available. You do not need to attempt another repair to demonstrate the fault; explain the symptoms and let the professional decide which tests are suitable."]}]);
coburgBookingArticle.sections.sort((a, b) => sectionOrder.indexOf(a.heading) - sectionOrder.indexOf(b.heading));
