// Generated from G-NAF-derived locality centroids (joelkoen/postcodes-au).
// Lists are the ten nearest distinct localities; they are not service guarantees.
export const generatedNearbySuburbs: Record<string, string[]> = {
  "Melbourne": [
    "West Melbourne",
    "Carlton",
    "Southbank",
    "Docklands",
    "South Wharf",
    "North Melbourne",
    "East Melbourne",
    "Fitzroy",
    "South Melbourne",
    "Collingwood"
  ],
  "St Albans": [
    "Kealba",
    "Cairnlea",
    "Keilor Downs",
    "Kings Park",
    "Albanvale",
    "Keilor",
    "Sunshine North",
    "Ardeer",
    "Delahey",
    "Deer Park"
  ],
  "South Melbourne": [
    "Southbank",
    "Albert Park",
    "South Wharf",
    "Melbourne",
    "Middle Park",
    "Docklands",
    "Port Melbourne",
    "St Kilda West",
    "Cremorne",
    "South Yarra"
  ],
  "Pakenham": [
    "Officer South",
    "Officer",
    "Nar Nar Goon North",
    "Nar Nar Goon",
    "Pakenham Upper",
    "Rythdale",
    "Pakenham South",
    "Beaconsfield",
    "Beaconsfield Upper",
    "Cardinia"
  ],
  "Bendigo": [
    "Ironbark",
    "Quarry Hill",
    "North Bendigo",
    "Long Gully",
    "Kennington",
    "West Bendigo",
    "Flora Hill",
    "East Bendigo",
    "Golden Square",
    "Golden Gully"
  ],
  "Geelong": [
    "South Geelong",
    "East Geelong",
    "Geelong West",
    "Newtown",
    "Drumcondra",
    "Thomson",
    "Manifold Heights",
    "Rippleside",
    "Newcomb",
    "North Geelong"
  ],
  "Melton": [
    "Kurunjang",
    "Melton West",
    "Melton South",
    "Harkness",
    "Brookfield",
    "Cobblebank",
    "Weir Views",
    "Strathtulloh",
    "Grangefields",
    "Thornhill Park"
  ],
  "Point Cook": [
    "Seabrook",
    "Altona Meadows",
    "Williams Landing",
    "Laverton",
    "Hoppers Crossing",
    "Werribee South",
    "Altona",
    "Werribee",
    "Truganina",
    "Laverton North"
  ],
  "Reservoir": [
    "Kingsbury",
    "Preston",
    "Thomastown",
    "Fawkner",
    "Coburg North",
    "Heidelberg West",
    "Thornbury",
    "Bundoora",
    "Heidelberg Heights",
    "Bellfield"
  ],
  "Richmond": [
    "Cremorne",
    "Abbotsford",
    "Burnley",
    "East Melbourne",
    "Collingwood",
    "South Yarra",
    "Fitzroy",
    "Hawthorn",
    "Toorak",
    "Clifton Hill"
  ],
  "St Kilda": [
    "St Kilda West",
    "Balaclava",
    "Windsor",
    "St Kilda East",
    "Elwood",
    "Prahran",
    "Ripponlea",
    "Middle Park",
    "Melbourne",
    "South Yarra"
  ],
  "Epping": [
    "Lalor",
    "Wollert",
    "Mill Park",
    "Thomastown",
    "South Morang",
    "Somerton",
    "Campbellfield",
    "Mernda",
    "Bundoora",
    "Watsonia North"
  ],
  "Footscray": [
    "Seddon",
    "Kingsville",
    "West Footscray",
    "Yarraville",
    "Kensington",
    "Maribyrnong",
    "Maidstone",
    "Ascot Vale",
    "Flemington",
    "Spotswood"
  ],
  "Glen Waverley": [
    "Mount Waverley",
    "Notting Hill",
    "Vermont South",
    "Burwood East",
    "Wheelers Hill",
    "Forest Hill",
    "Blackburn South",
    "Oakleigh East",
    "Mulgrave",
    "Clayton"
  ],
  "Fitzroy": [
    "Collingwood",
    "Carlton",
    "East Melbourne",
    "Carlton North",
    "Clifton Hill",
    "Fitzroy North",
    "Melbourne",
    "Abbotsford",
    "Princes Hill",
    "North Melbourne"
  ],
  "Box Hill": [
    "Mont Albert",
    "Box Hill North",
    "Box Hill South",
    "Mont Albert North",
    "Surrey Hills",
    "Blackburn",
    "Blackburn South",
    "Blackburn North",
    "Burwood",
    "Balwyn"
  ],
  "Hawthorn": [
    "Hawthorn East",
    "Burnley",
    "Kew",
    "Kooyong",
    "Toorak",
    "Richmond",
    "Deepdene",
    "Abbotsford",
    "Cremorne",
    "Kew East"
  ],
  "Essendon": [
    "Essendon North",
    "Aberfeldie",
    "Strathmore",
    "Moonee Ponds",
    "Essendon West",
    "Pascoe Vale South",
    "Niddrie",
    "Essendon Fields",
    "Ascot Vale",
    "Brunswick West"
  ],
  "Ringwood": [
    "Ringwood East",
    "Ringwood North",
    "Heathmont",
    "Mitcham",
    "Park Orchards",
    "Croydon South",
    "Vermont",
    "Warranwood",
    "Wantirna",
    "Bayswater North"
  ],
  "Brighton": [
    "Gardenvale",
    "Brighton East",
    "Elsternwick",
    "Caulfield South",
    "Elwood",
    "Ripponlea",
    "Hampton",
    "Mckinnon",
    "Caulfield",
    "Bentleigh"
  ],
  "Narre Warren": [
    "Narre Warren North",
    "Hallam",
    "Hampton Park",
    "Berwick",
    "Harkaway",
    "Narre Warren South",
    "Eumemmerring",
    "Endeavour Hills",
    "Lynbrook",
    "Doveton"
  ],
  "Mornington": [
    "Mount Martha",
    "Mount Eliza",
    "Moorooduc",
    "Tuerong",
    "Frankston South",
    "Baxter",
    "Safety Beach",
    "Somerville",
    "Frankston",
    "Tyabb"
  ],
  "Brunswick": [
    "Brunswick East",
    "Brunswick West",
    "Princes Hill",
    "Parkville",
    "Carlton North",
    "Coburg",
    "Fitzroy North",
    "Travancore",
    "Pascoe Vale South",
    "Northcote"
  ],
  "Dandenong": [
    "Doveton",
    "Dandenong North",
    "Eumemmerring",
    "Noble Park",
    "Keysborough",
    "Noble Park North",
    "Dandenong South",
    "Endeavour Hills",
    "Springvale South",
    "Hallam"
  ],
  "Frankston": [
    "Frankston South",
    "Frankston North",
    "Seaford",
    "Langwarrin",
    "Baxter",
    "Langwarrin South",
    "Mount Eliza",
    "Carrum Downs",
    "Skye",
    "Carrum"
  ],
  "Kew": [
    "Kew East",
    "Hawthorn",
    "Deepdene",
    "Alphington",
    "Hawthorn East",
    "Abbotsford",
    "Richmond",
    "Burnley",
    "Fairfield",
    "Clifton Hill"
  ],
  "Caroline Springs": [
    "Burnside Heights",
    "Burnside",
    "Taylors Hill",
    "Kings Park",
    "Deanside",
    "Albanvale",
    "Delahey",
    "Fraser Rise",
    "Ravenhall",
    "Deer Park"
  ],
  "Williamstown": [
    "Williamstown North",
    "Newport",
    "Spotswood",
    "South Kingsville",
    "Seaholme",
    "Port Melbourne",
    "Altona North",
    "Yarraville",
    "Albert Park",
    "Kingsville"
  ],
  "Kensington": [
    "Flemington",
    "Travancore",
    "Ascot Vale",
    "North Melbourne",
    "Parkville",
    "Footscray",
    "West Melbourne",
    "Moonee Ponds",
    "Docklands",
    "Seddon"
  ],
  "Blackburn": [
    "Blackburn North",
    "Blackburn South",
    "Nunawading",
    "Box Hill",
    "Box Hill North",
    "Forest Hill",
    "Box Hill South",
    "Burwood East",
    "Mont Albert",
    "Mont Albert North"
  ],
  "Thornbury": [
    "Northcote",
    "Preston",
    "Fairfield",
    "Brunswick East",
    "Bellfield",
    "Alphington",
    "Fitzroy North",
    "Ivanhoe",
    "Clifton Hill",
    "Coburg"
  ],
  "Craigieburn": [
    "Yuroke",
    "Roxburgh Park",
    "Mickleham",
    "Greenvale",
    "Somerton",
    "Meadow Heights",
    "Oaklands Junction",
    "Coolaroo",
    "Kalkallo",
    "Donnybrook"
  ],
  "North Melbourne": [
    "West Melbourne",
    "Carlton",
    "Parkville",
    "Melbourne",
    "Kensington",
    "Travancore",
    "Docklands",
    "Flemington",
    "Princes Hill",
    "Carlton North"
  ],
  "Berwick": [
    "Beaconsfield",
    "Narre Warren South",
    "Narre Warren",
    "Harkaway",
    "Cranbourne North",
    "Guys Hill",
    "Clyde North",
    "Officer",
    "Hampton Park",
    "Narre Warren North"
  ],
  "Hoppers Crossing": [
    "Tarneit",
    "Williams Landing",
    "Werribee",
    "Point Cook",
    "Truganina",
    "Seabrook",
    "Wyndham Vale",
    "Laverton",
    "Altona Meadows",
    "Mount Cottrell"
  ],
  "Altona": [
    "Seaholme",
    "Altona Meadows",
    "Laverton",
    "Altona North",
    "Laverton North",
    "Williamstown North",
    "Brooklyn",
    "Seabrook",
    "Newport",
    "South Kingsville"
  ],
  "Bentleigh": [
    "Mckinnon",
    "Hampton East",
    "Brighton East",
    "Ormond",
    "Bentleigh East",
    "Moorabbin",
    "Hampton",
    "Highett",
    "Caulfield South",
    "Glen Huntly"
  ],
  "Moorabbin": [
    "Highett",
    "Hampton East",
    "Bentleigh East",
    "Bentleigh",
    "Cheltenham",
    "Heatherton",
    "Mckinnon",
    "Sandringham",
    "Oakleigh South",
    "Hampton"
  ],
  "Bundoora": [
    "Watsonia North",
    "Watsonia",
    "Macleod",
    "Kingsbury",
    "Mill Park",
    "Greensborough",
    "Thomastown",
    "Yallambie",
    "Reservoir",
    "Rosanna"
  ],
  "Preston": [
    "Thornbury",
    "Reservoir",
    "Bellfield",
    "Heidelberg West",
    "Northcote",
    "Coburg",
    "Coburg North",
    "Kingsbury",
    "Fairfield",
    "Heidelberg Heights"
  ],
  "Doncaster": [
    "Mont Albert North",
    "Box Hill North",
    "Templestowe Lower",
    "Bulleen",
    "Doncaster East",
    "Templestowe",
    "Blackburn North",
    "Balwyn North",
    "Box Hill",
    "Mont Albert"
  ],
  "Northcote": [
    "Thornbury",
    "Fairfield",
    "Fitzroy North",
    "Clifton Hill",
    "Brunswick East",
    "Alphington",
    "Carlton North",
    "Princes Hill",
    "Brunswick",
    "Collingwood"
  ],
  "Coburg": [
    "Coburg North",
    "Pascoe Vale South",
    "Brunswick",
    "Brunswick West",
    "Brunswick East",
    "Pascoe Vale",
    "Preston",
    "Thornbury",
    "Princes Hill",
    "Hadfield"
  ],
  "Cremorne": [
    "South Yarra",
    "Richmond",
    "Burnley",
    "East Melbourne",
    "Melbourne",
    "Toorak",
    "Abbotsford",
    "Prahran",
    "Southbank",
    "Windsor"
  ],
  "Werribee": [
    "Wyndham Vale",
    "Cocoroc",
    "Mambourin",
    "Hoppers Crossing",
    "Manor Lakes",
    "Tarneit",
    "Werribee South",
    "Point Cook",
    "Williams Landing",
    "Seabrook"
  ],
  "Camberwell": [
    "Canterbury",
    "Glen Iris",
    "Hawthorn East",
    "Surrey Hills",
    "Deepdene",
    "Ashburton",
    "Kooyong",
    "Balwyn",
    "Mont Albert",
    "Hawthorn"
  ],
  "Sunbury": [
    "Diggers Rest",
    "Wildwood",
    "Gisborne South",
    "Bulla",
    "Oaklands Junction",
    "Calder Park",
    "Plumpton",
    "Clarkefield",
    "Toolern Vale",
    "Hillside"
  ],
  "Sunshine": [
    "Albion",
    "Braybrook",
    "Tottenham",
    "Sunshine West",
    "Sunshine North",
    "Ardeer",
    "West Footscray",
    "Maidstone",
    "Brooklyn",
    "Avondale Heights"
  ],
  "Port Melbourne": [
    "Albert Park",
    "South Wharf",
    "Docklands",
    "South Melbourne",
    "Southbank",
    "Middle Park",
    "West Melbourne",
    "Melbourne",
    "St Kilda West",
    "North Melbourne"
  ],
  "Balwyn": [
    "Deepdene",
    "Canterbury",
    "Balwyn North",
    "Surrey Hills",
    "Mont Albert",
    "Mont Albert North",
    "Kew East",
    "Camberwell",
    "Hawthorn East",
    "Box Hill"
  ],
  "Carlton": [
    "Fitzroy",
    "Melbourne",
    "North Melbourne",
    "West Melbourne",
    "Carlton North",
    "Collingwood",
    "East Melbourne",
    "Princes Hill",
    "Parkville",
    "Fitzroy North"
  ],
  "Tarneit": [
    "Mount Cottrell",
    "Hoppers Crossing",
    "Truganina",
    "Wyndham Vale",
    "Werribee",
    "Williams Landing",
    "Manor Lakes",
    "Mambourin",
    "Seabrook",
    "Point Cook"
  ],
  "Cheltenham": [
    "Mentone",
    "Heatherton",
    "Highett",
    "Moorabbin",
    "Beaumaris",
    "Moorabbin Airport",
    "Parkdale",
    "Black Rock",
    "Hampton East",
    "Sandringham"
  ],
  "Newport": [
    "Williamstown North",
    "South Kingsville",
    "Spotswood",
    "Williamstown",
    "Altona North",
    "Yarraville",
    "Kingsville",
    "Seaholme",
    "Brooklyn",
    "Seddon"
  ],
  "Templestowe": [
    "Doncaster East",
    "Templestowe Lower",
    "Doncaster",
    "Lower Plenty",
    "Bulleen",
    "Donvale",
    "Montmorency",
    "Blackburn North",
    "Eltham",
    "Box Hill North"
  ],
  "Hampton": [
    "Sandringham",
    "Hampton East",
    "Brighton East",
    "Bentleigh",
    "Highett",
    "Brighton",
    "Black Rock",
    "Mckinnon",
    "Moorabbin",
    "Gardenvale"
  ],
  "Lalor": [
    "Thomastown",
    "Epping",
    "Mill Park",
    "Campbellfield",
    "Reservoir",
    "Bundoora",
    "Kingsbury",
    "Fawkner",
    "Somerton",
    "Wollert"
  ],
  "Mill Park": [
    "Bundoora",
    "South Morang",
    "Epping",
    "Lalor",
    "Watsonia North",
    "Thomastown",
    "Plenty",
    "Watsonia",
    "Greensborough",
    "Kingsbury"
  ],
  "Bulleen": [
    "Templestowe Lower",
    "Balwyn North",
    "Heidelberg",
    "Eaglemont",
    "Ivanhoe East",
    "Doncaster",
    "Viewbank",
    "Rosanna",
    "Mont Albert North",
    "Ivanhoe"
  ],
  "Malvern": [
    "Armadale",
    "Kooyong",
    "Caulfield North",
    "Glen Iris",
    "Toorak",
    "Caulfield East",
    "St Kilda East",
    "Caulfield",
    "Prahran",
    "Malvern East"
  ],
  "Prahran": [
    "Windsor",
    "South Yarra",
    "St Kilda East",
    "Toorak",
    "St Kilda",
    "Armadale",
    "Melbourne",
    "Balaclava",
    "St Kilda West",
    "Cremorne"
  ],
  "Mont Albert": [
    "Surrey Hills",
    "Box Hill",
    "Mont Albert North",
    "Box Hill North",
    "Box Hill South",
    "Balwyn",
    "Canterbury",
    "Balwyn North",
    "Burwood",
    "Deepdene"
  ],
  "Burwood": [
    "Box Hill South",
    "Ashwood",
    "Burwood East",
    "Surrey Hills",
    "Blackburn South",
    "Mount Waverley",
    "Ashburton",
    "Chadstone",
    "Box Hill",
    "Mont Albert"
  ],
  "Springvale": [
    "Clayton South",
    "Springvale South",
    "Mulgrave",
    "Noble Park",
    "Noble Park North",
    "Clayton",
    "Clarinda",
    "Dingley Village",
    "Notting Hill",
    "Wheelers Hill"
  ],
  "Clifton Hill": [
    "Fitzroy North",
    "Collingwood",
    "Abbotsford",
    "Fitzroy",
    "Northcote",
    "Carlton North",
    "Fairfield",
    "East Melbourne",
    "Princes Hill",
    "Brunswick East"
  ],
  "Deanside": [
    "Caroline Springs",
    "Fraser Rise",
    "Taylors Hill",
    "Ravenhall",
    "Rockbank",
    "Burnside Heights",
    "Plumpton",
    "Truganina",
    "Derrimut",
    "Hillside"
  ],
  "Mount Waverley": [
    "Chadstone",
    "Ashwood",
    "Burwood East",
    "Oakleigh East",
    "Glen Waverley",
    "Burwood",
    "Notting Hill",
    "Huntingdale",
    "Oakleigh",
    "Ashburton"
  ],
  "Strathmore": [
    "Essendon North",
    "Essendon Fields",
    "Oak Park",
    "Essendon",
    "Pascoe Vale",
    "Pascoe Vale South",
    "Niddrie",
    "Strathmore Heights",
    "Airport West",
    "Aberfeldie"
  ],
  "Thomastown": [
    "Lalor",
    "Reservoir",
    "Kingsbury",
    "Bundoora",
    "Fawkner",
    "Mill Park",
    "Epping",
    "Campbellfield",
    "Coburg North",
    "Watsonia North"
  ],
  "Toorak": [
    "Burnley",
    "Armadale",
    "Prahran",
    "Kooyong",
    "South Yarra",
    "Windsor",
    "Cremorne",
    "Malvern",
    "Hawthorn",
    "St Kilda East"
  ],
  "Chadstone": [
    "Ashwood",
    "Oakleigh",
    "Ashburton",
    "Hughesdale",
    "Mount Waverley",
    "Oakleigh East",
    "Huntingdale",
    "Murrumbeena",
    "Malvern East",
    "Burwood"
  ],
  "Cranbourne": [
    "Cranbourne West",
    "Cranbourne East",
    "Cranbourne North",
    "Junction Village",
    "Lyndhurst",
    "Botanic Ridge",
    "Cranbourne South",
    "Narre Warren South",
    "Lynbrook",
    "Sandhurst"
  ],
  "Wantirna": [
    "Wantirna South",
    "Heathmont",
    "Bayswater",
    "Vermont",
    "Vermont South",
    "Knoxfield",
    "Ringwood",
    "Scoresby",
    "Boronia",
    "Mitcham"
  ],
  "Bayswater": [
    "Boronia",
    "Bayswater North",
    "Heathmont",
    "Wantirna",
    "Croydon South",
    "Ringwood East",
    "Wantirna South",
    "Kilsyth South",
    "Ferntree Gully",
    "The Basin"
  ],
  "Greenvale": [
    "Meadow Heights",
    "Roxburgh Park",
    "Attwood",
    "Coolaroo",
    "Westmeadows",
    "Yuroke",
    "Craigieburn",
    "Dallas",
    "Somerton",
    "Gladstone Park"
  ],
  "Ferntree Gully": [
    "Knoxfield",
    "Boronia",
    "Upper Ferntree Gully",
    "Lysterfield",
    "The Basin",
    "Tremont",
    "Wantirna South",
    "Bayswater",
    "Scoresby",
    "Ferny Creek"
  ],
  "Yarraville": [
    "Kingsville",
    "Seddon",
    "Spotswood",
    "South Kingsville",
    "West Footscray",
    "Footscray",
    "Newport",
    "Tottenham",
    "Altona North",
    "Brooklyn"
  ],
  "Seaford": [
    "Frankston North",
    "Carrum",
    "Carrum Downs",
    "Frankston",
    "Patterson Lakes",
    "Bonbeach",
    "Skye",
    "Sandhurst",
    "Chelsea",
    "Frankston South"
  ],
  "South Yarra": [
    "Cremorne",
    "Melbourne",
    "Prahran",
    "Windsor",
    "Burnley",
    "Toorak",
    "Richmond",
    "St Kilda West",
    "St Kilda",
    "South Melbourne"
  ],
  "Ascot Vale": [
    "Moonee Ponds",
    "Flemington",
    "Travancore",
    "Kensington",
    "Maribyrnong",
    "Aberfeldie",
    "Brunswick West",
    "Footscray",
    "Parkville",
    "Essendon"
  ],
  "South Morang": [
    "Mill Park",
    "Mernda",
    "Yarrambat",
    "Plenty",
    "Epping",
    "Doreen",
    "Watsonia North",
    "Bundoora",
    "St Helena",
    "Lalor"
  ]
,
  "Ballarat": ["Ballarat Central", "Ballarat East", "Ballarat North", "Ballarat West", "Bakery Hill", "Golden Point", "Lake Wendouree", "Redan", "Soldiers Hill", "Newington"]
};
