import type { Article } from './articles';
export const hotWaterGuide: Article = {
 title:'How Long Does a Hot Water System Last?',slug:'how-long-does-a-hot-water-system-last',metaTitle:'Hot Water System Lifespan & Replacement Signs | Grade A Plumbing',metaDescription:'Understand what affects hot water system lifespan, which warning signs need assessment and how Melbourne households can plan repair or replacement.',author:'Grade A Plumbing',publishedDate:'2026-09-20',updatedDate:'2026-10-01',status:'published',locationSlugs:['melbourne'],excerpt:'There is no single expiry date for every hot water system. Learn how condition, system type and service history guide a sensible repair or replacement decision.',relatedServices:['hot-water'],relatedArticles:['before-booking-a-plumber-in-coburg-photos-access-and-questions-to-prepare'],
 sources:[{title:'Australian Government: hot water system types and selection',url:'https://www.energy.gov.au/households/hot-water-systems'},{title:'Building and Plumbing Commission: engaging a plumber',url:'https://www.bpc.vic.gov.au/home-owners/before-you-start-building/engaging-a-plumber'}],
 faq:[{question:'Can you give an exact lifespan for my system?',answer:'Not from age alone. The model, installation, maintenance and current condition need assessment. A warranty period is not a guaranteed service life.'},{question:'Does a leak mean the whole unit needs replacement?',answer:'Not necessarily. A connection or component leak differs from a deteriorated storage tank. Have the source identified rather than replacing the unit based on a photograph.'},{question:'Should I change the temperature to improve performance?',answer:'Do not change internal controls or remove covers. Explain the symptoms to a qualified professional and follow the manufacturer’s user instructions.'},{question:'Is a heat pump suitable for every Melbourne property?',answer:'Suitability depends on the chosen model, installation space, airflow, noise considerations, electrical supply and household demand. Ask for a property-specific assessment.'}],
 sections:[
 {heading:'The short answer: condition matters more than a universal age limit',paragraphs:[
 'A hot water system does not become unserviceable on a single birthday. Two units installed in the same year can have different maintenance histories, usage patterns and faults. A meaningful lifespan estimate starts with the exact model and its condition, not a generic number copied from another product. If you cannot identify the system, photograph its accessible label without opening panels or moving equipment.',
 'This guide deliberately does not promise a fixed number of years. That would blur the difference between expected performance, manufacturer warranty and the condition of your own installation. A system may continue working beyond a warranty period, while a fault within that period may still need investigation. Keep purchase records and warranty documents so any applicable claim can be assessed before you approve paid work.',
 'For Melbourne households, the practical question is usually whether the existing unit remains reliable and appropriate for daily demand. If there is an active leak, a safety concern or no hot water, arrange assessment rather than waiting for an age threshold. If it is working normally, use the opportunity to understand its maintenance requirements and plan ahead instead of replacing it solely because someone describes it as old.'
 ]},
 {heading:'Identify the kind of system you have',paragraphs:[
 'The Australian Government distinguishes storage systems, which keep water in a tank, from instantaneous systems, which heat water as needed. It also describes electric, gas, solar and heat pump options. That distinction matters because the components being assessed and the replacement options are not identical. An outdoor cabinet, a roof collector and a storage cylinder may belong to different arrangements.',
 'Write down the brand, model and any installation date you can confirm from your records. Do not estimate the installation year from appearance alone. If the label shows a manufacturing date, tell the plumber that it is a manufacturing date rather than presenting it as the date the unit entered service. Also mention any separate booster or controller and whether more than one unit serves the property.',
 'A useful enquiry describes household demand as well as the hardware. Explain whether you have one bathroom or several, whether hot water runs out during consecutive showers and whether the problem affects every outlet. This information helps distinguish the question of system capacity from a recent performance fault. It does not establish a diagnosis, but it gives the assessment a clearer starting point.'
 ]},
 {heading:'Warning signs worth recording',paragraphs:[
 'Record what has changed: inconsistent temperature, a shorter supply of hot water, water around the unit, discoloured water or an unfamiliar operating sound. Note when each symptom occurs and whether it affects hot water only. A problem isolated to one tap may require a different investigation from a change throughout the building. Avoid assuming that every symptom proves the tank has failed.',
 'Take a wide photograph of the installation and a closer view of visible water or staining from a safe position. Include the surrounding access area so the plumber can understand any restrictions. Do not recreate a fault by running appliances repeatedly, touching hot pipework or opening protective covers. If the installation is difficult to reach, explain that during booking rather than attempting unsafe access.',
 'Treat water near electrical equipment, a suspected gas problem or immediate danger as a safety issue, not a routine maintenance exercise. Keep people clear and obtain appropriate urgent assistance; call emergency services where there is immediate danger. This article is not a gas or electrical troubleshooting procedure. The person attending may need to coordinate more than one qualified trade before the system can safely return to use.'
 ]},
 {heading:'Service history and model-specific maintenance',paragraphs:[
 'Find the user manual for your actual model and keep a record of previous inspections and repairs. Maintenance instructions are product-specific, so a schedule intended for another system should not be treated as universal. Ask the professional assessing your unit which manufacturer requirements apply, what has already been completed and what remains appropriate for its current condition.',
 'A history of repeated repairs is useful evidence, but it needs context. Several invoices may relate to separate components, installation changes or a recurring unresolved fault. Ask for a plain-language explanation of whether the current issue is connected to previous work. A list of parts replaced is less useful than understanding whether another repair is likely to provide a reasonable period of reliable operation.',
 'Avoid treating online maintenance advice as permission to dismantle plumbing or electrical equipment. Your role can be to organise documents, record symptoms and keep accessible space clear. Ask about safe user-level checks only where the manufacturer provides them. Work involving the installation itself should be assessed by professionals authorised for the relevant work rather than attempted to extend a system’s life cheaply.'
 ]},
 {heading:'Compare repair with replacement fairly',paragraphs:[
 'Ask the plumber to identify the confirmed fault, the proposed remedy and the limits of that remedy. Repairing an accessible component is a different proposition from addressing deterioration affecting the main unit. A useful recommendation explains what the repair fixes and what it does not fix. Ask whether there are unresolved conditions that could change the scope after initial investigation.',
 'When comparing quotes, request a consistent scope. Check whether removal, installation changes, required electrical work, commissioning and disposal are included where relevant. Do not compare an equipment-only figure with a complete installed proposal. Ask which assumptions the quote makes about access and existing connections, and how variations would be discussed before additional work proceeds.',
 'Replacement also raises a selection question. The government’s guidance notes that heat pump and solar arrangements differ from conventional systems and that model suitability matters in colder conditions. Ask how the proposed unit suits your space and usage rather than assuming the most promoted technology is automatically best. Confirm any incentive eligibility using current official information before relying on a rebate in your budget.'
 ]},
 {heading:'Prepare for an interruption before it becomes urgent',paragraphs:[
 'If your existing system is still operating but you are considering replacement, decide what information you need before requesting quotes. Record normal household demand, the location of the equipment and any restrictions on access. Ask whether the proposed work requires another trade, a change to the installation layout or approval from a property representative. Planning these details is more useful than choosing a replacement from a photograph alone.',
 'Discuss how a planned interruption will affect the people using the property. A home, shared building and customer-facing business may have different requirements. Ask what arrangements are possible, without assuming temporary equipment is included or available. Confirm what is included in writing and keep the contact details for follow-up. That preparation does not guarantee an uninterrupted supply, but it helps you make an informed choice instead of rushing an unfamiliar decision after a breakdown.'
 ]},
 {heading:'Plan the appointment and keep useful records',paragraphs:[
 'For a planned visit, provide the address, model details, symptom timeline and any access restrictions. In an apartment or rental property, confirm who can approve work and whether building management must coordinate access or a shutdown. Tell the team if the system serves several occupancies. Do not promise other residents a restoration time until the assessment and work arrangements are confirmed.',
 'After assessment, keep the written recommendation, invoice and relevant product information together. Ask what warning signs should prompt another call and what model-specific maintenance is recommended. Where documentation or a plumbing compliance certificate is required for the work, clarify who supplies it. Victoria’s Building and Plumbing Commission provides guidance on checking a practitioner’s licence or registration and the authorised work classes.',
 'Need help deciding what to do next? Contact Grade A Plumbing on (02) 5837 5457 or email support@gradeaplumbing.store with your suburb, system details and a brief description. Ask for current availability and an appropriate assessment rather than a guaranteed diagnosis from photos. The related hot water service page explains how to request help; the booking guide below shows which information to prepare before the visit.'
 ]}
 ]
};
