import type { LocationConfig } from "./locations";

export type ServiceDefinition = {
  slug: string;
  label: string;
  shortLabel: string;
  serviceType: string;
  title: (location: string) => string;
  h1: (location: string) => string;
  description: (location: string) => string;
  intro: (location: string) => string;
  sections: { title: string; text: string }[];
  related: string[];
  faqs: (location: string) => { question: string; answer: string }[];
};

const commonFaq = (service: string, location: string) => [
  { question: `Do you provide ${service.toLowerCase()} in ${location}?`, answer: `Yes. Contact Grade A Plumbing to confirm current availability for ${service.toLowerCase()} in ${location} and nearby service areas.` },
  { question: "Can I request a quote before work starts?", answer: "Tell us what is happening and we will explain the appropriate assessment and pricing process before work proceeds wherever possible." }
];

const service = (definition: Omit<ServiceDefinition, "faqs">): ServiceDefinition => ({
  ...definition,
  faqs: (location) => commonFaq(definition.label, location)
});

export const services: ServiceDefinition[] = [
  service({ slug: "blocked-drains", label: "Blocked Drains", shortLabel: "Blocked drains", serviceType: "Blocked drain plumbing", title: l => `Blocked Drains ${l} | Drain Plumber | Grade A Plumbing`, h1: l => `Blocked Drain Plumber in ${l}`, description: l => `Blocked drains in ${l}? Get help with blocked toilets, sinks, sewer lines and stormwater drains from Grade A Plumbing.`, intro: l => `Slow drains, gurgling pipes, unpleasant smells and overflows can all point to a blockage. We help ${l} properties identify the likely cause and choose a practical way to restore flow.`, sections: [{ title: "Blocked drain services", text: "Help with blocked toilets, kitchen sinks, sewer lines and stormwater drainage." }, { title: "How blocked drains are cleared", text: "The appropriate method depends on access, pipe condition and the cause. Assessment may identify whether clearing, inspection or repair is the sensible next step." }, { title: "Common causes", text: "Tree roots, grease, foreign objects, damaged pipework and stormwater debris are common causes of repeat blockages." }, { title: "High-pressure water jetting", text: "Where suitable, water jetting can remove built-up material from drainage lines without relying on repeated chemical treatments." }], related: ["sewer-repairs", "pipe-relining", "emergency-plumber"] }),
  service({ slug: "sewer-repairs", label: "Sewer Repairs", shortLabel: "Sewer repairs", serviceType: "Sewer repair", title: l => `Sewer Repairs ${l} | Sewer Plumber | Grade A Plumbing`, h1: l => `Sewer Repairs in ${l}`, description: l => `Sewer repair services in ${l} for recurring blockages, damaged sewer lines and wastewater problems. Talk to Grade A Plumbing.`, intro: l => `Recurring blockages, wastewater overflow and persistent drain odours may point to a sewer line problem. Grade A Plumbing helps ${l} property owners understand the fault and available repair options.`, sections: [{ title: "Signs of sewer damage", text: "Repeated blockages, wet patches, odours and multiple slow fixtures can indicate a deeper drainage issue." }, { title: "Sewer inspection and diagnosis", text: "A sound repair starts by locating the fault and understanding the pipe condition." }, { title: "Repair options", text: "The right solution may involve clearing, a targeted repair or relining, depending on the confirmed problem." }], related: ["blocked-drains", "pipe-relining", "emergency-plumber"] }),
  service({ slug: "pipe-relining", label: "Pipe Relining", shortLabel: "Pipe relining", serviceType: "Pipe relining", title: l => `Pipe Relining ${l} | No-Dig Pipe Repair | Grade A Plumbing`, h1: l => `Pipe Relining in ${l}`, description: l => `Explore pipe relining in ${l} for eligible cracked or damaged drains. Grade A Plumbing can assess whether no-dig repair is suitable.`, intro: l => `Pipe relining can repair some damaged drain sections from inside the existing pipe. Suitability depends on inspection findings, access and the type and extent of damage.`, sections: [{ title: "When relining may help", text: "Relining may suit certain cracked, root-affected or leaking drainage pipes where the host pipe can be prepared correctly." }, { title: "Inspection comes first", text: "A drain inspection helps establish whether relining, excavation or another repair is appropriate." }, { title: "A targeted repair option", text: "Where suitable, relining can reduce excavation and restore a continuous internal pipe surface." }], related: ["blocked-drains", "sewer-repairs"] }),
  service({ slug: "hot-water", label: "Hot Water", shortLabel: "Hot water", serviceType: "Hot water repair and installation", title: l => `Hot Water Systems ${l} | Repair & Installation | Grade A Plumbing`, h1: l => `Hot Water Plumber in ${l}`, description: l => `Hot water repairs, replacement and installation in ${l}. Get practical help with leaks, temperature issues and system faults.`, intro: l => `No hot water, leaking equipment, low pressure or inconsistent temperature can disrupt the whole property. We help ${l} customers assess repair and replacement options without assuming every fault needs a new system.`, sections: [{ title: "Hot water repairs", text: "Faults can involve valves, plumbing connections, controls, the energy supply or the unit itself." }, { title: "Replacement and installation", text: "When repair no longer represents good value, the property needs and available services should guide replacement." }, { title: "Repair versus replacement", text: "Condition, fault type, reliability and repair value all matter when comparing options." }], related: ["gas-plumbing", "emergency-plumber", "commercial-plumbing"] }),
  service({ slug: "emergency-plumber", label: "Emergency Plumbing", shortLabel: "Emergency plumber", serviceType: "Emergency plumbing", title: l => `Emergency Plumber ${l} | Grade A Plumbing`, h1: l => `Emergency Plumber in ${l}`, description: l => `Need an emergency plumber in ${l}? Call Grade A Plumbing for urgent leaks, burst pipes, blocked drains and plumbing faults.`, intro: l => `Major leaks, burst pipes, overflowing drains and loss of essential plumbing can require prompt attention. Call to explain the issue and confirm the soonest available option in ${l}.`, sections: [{ title: "Urgent plumbing problems", text: "Burst pipes, uncontrolled leaks, wastewater overflows and essential-service failures can cause damage or health risks." }, { title: "What to do first", text: "If safe, isolate the affected water supply and keep people away from wastewater or electrical hazards before calling." }, { title: "Clear next steps", text: "We will ask about the fault, property and urgency so the most appropriate next action can be discussed." }], related: ["burst-pipe-repair", "blocked-drains", "hot-water"] }),
  service({ slug: "burst-pipe-repair", label: "Burst Pipe Repair", shortLabel: "Burst pipes", serviceType: "Burst pipe repair", title: l => `Burst Pipe Repair ${l} | Grade A Plumbing`, h1: l => `Burst Pipe Repair in ${l}`, description: l => `Burst or leaking pipe in ${l}? Call Grade A Plumbing for assessment, isolation guidance and pipe repair.`, intro: l => `A burst pipe can release water quickly into walls, floors, cabinetry or outdoor areas. If safe, turn off the water supply and contact Grade A Plumbing for help in ${l}.`, sections: [{ title: "Signs of a burst pipe", text: "Sudden pressure loss, running-water sounds, damp surfaces and unexpected pooling may indicate a failed pipe." }, { title: "Limit water damage", text: "Safe isolation and prompt assessment can reduce the spread of water while the repair is planned." }, { title: "Repairing the fault", text: "Access, pipe material, condition and the failure location determine the suitable repair." }], related: ["emergency-plumber", "commercial-plumbing"] }),
  service({ slug: "gas-plumbing", label: "Gas Plumbing", shortLabel: "Gas plumbing", serviceType: "Gas plumbing", title: l => `Gas Plumber ${l} | Gas Plumbing Services | Grade A Plumbing`, h1: l => `Gas Plumber in ${l}`, description: l => `Gas plumbing services in ${l}. Contact Grade A Plumbing about gas leaks, appliance connections and gas pipework.`, intro: l => `Gas plumbing requires appropriate care and qualified work. If you suspect a leak, avoid flames and switches, move to safety and contact the relevant emergency authority before arranging plumbing assistance.`, sections: [{ title: "Gas plumbing services", text: "Gas pipework, connections and fault assessment should be handled by an appropriately qualified professional." }, { title: "Suspected gas leaks", text: "Treat gas smells seriously. Avoid ignition sources, ventilate only if safe and follow emergency authority advice." }, { title: "Gas hot water", text: "Gas supply and plumbing considerations may form part of hot water fault finding or replacement work." }], related: ["hot-water", "emergency-plumber"] }),
  service({ slug: "commercial-plumbing", label: "Commercial Plumbing", shortLabel: "Commercial plumbing", serviceType: "Commercial plumbing", title: l => `Commercial Plumber ${l} | Grade A Plumbing`, h1: l => `Commercial Plumber in ${l}`, description: l => `Commercial plumbing in ${l} for offices, shops, hospitality, facilities and managed properties. Request service from Grade A Plumbing.`, intro: l => `Commercial plumbing needs clear communication around access, trading, staff and tenants. We support ${l} businesses and managed properties with repairs, maintenance and urgent plumbing enquiries.`, sections: [{ title: "Commercial property types", text: "Support is available for offices, shops, hospitality venues, facilities and managed properties, subject to job requirements." }, { title: "Repairs and maintenance", text: "Drainage, amenities, leaks, fixtures and hot water are common commercial plumbing needs." }, { title: "Site communication", text: "Access, operational constraints and the recommended work should be clear before the job proceeds." }], related: ["blocked-drains", "hot-water", "emergency-plumber"] })
];

export const serviceBySlug = new Map(services.map(item => [item.slug, item]));

export function serviceUrl(serviceSlug: string) { return `/${serviceSlug}/`; }
export function locationHasService(location: LocationConfig) {
  return location.tier === 1 || location.slug === "melbourne" || Boolean(location.address);
}
