"use client";
import {useEffect,useState} from "react";
export function BrowserWorkerPanel(){
 const [status,setStatus]=useState<{enabled:boolean;lastSeenAt?:string;expiresAt?:number}|null>(null);
 const [manual,setManual]=useState<{ok?:boolean;running?:boolean;lastRun?:{startedAt:string;finishedAt:string;code:number;output:string};port?:number}|null>(null);
 const [error,setError]=useState("");
 async function refresh(){setError("");try{const response=await fetch("/api/automation/browser",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setStatus(data);await checkManual();}catch(e){setError(e instanceof Error?e.message:"Could not check browser worker.");}}
 async function checkManual(){try{const response=await fetch("http://127.0.0.1:53683/status",{cache:"no-store"});setManual(await response.json());}catch{setManual(null);}}
 async function runManual(){setError("");try{const response=await fetch("http://127.0.0.1:53683/run",{method:"POST"});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Could not start browser publishing.");setManual(data);setTimeout(()=>void checkManual(),4000);}catch(e){setError(e instanceof Error?e.message:"Start the GMB AutoPilot Manual Button Server on this computer, then click this again.");}}
 async function openGoogleLogin(){setError("");try{const response=await fetch("http://127.0.0.1:53683/google-login",{method:"POST"});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Could not open Google sign-in.");setManual(data);setTimeout(()=>void checkManual(),4000);}catch(e){setError(e instanceof Error?e.message:"Start the GMB AutoPilot Manual Button Server on this computer, then click this again.");}}
 useEffect(()=>{void refresh();const interval=setInterval(()=>void refresh(),30000);return()=>clearInterval(interval);},[]);
 useEffect(()=>{void checkManual();const interval=setInterval(()=>void checkManual(),5000);return()=>clearInterval(interval);},[]);
 const online=!!status?.lastSeenAt&&Date.now()-Date.parse(status.lastSeenAt)<6*60000;
 return <section className="auto-panel"><div className="auto-panel-heading"><h2>Browser publishing</h2><p>Use the signed-in Microsoft Edge profile on this computer. No Google API quota is needed.</p></div><div className="auto-toolbar"><span className={`auto-badge ${online?"green":"neutral"}`}>{status?.enabled?(online?"Cloud pairing active":"Cloud pairing idle"):"Cloud pairing off"}</span><span className={`auto-badge ${manual?"green":"neutral"}`}>{manual?manual.running?"Browser runner busy":"Browser runner ready":"Browser runner closed"}</span><button className="auto-button" onClick={()=>void refresh()}>Check connection</button><button className="auto-button" disabled={manual?.running} onClick={()=>void openGoogleLogin()}>Open secure Edge sign-in</button><button className="auto-button primary" disabled={!manual||manual.running} onClick={()=>void runManual()}>{manual?.running?"Running browser":"Run browser posts now"}</button>{status?.enabled&&<button className="auto-button" onClick={async()=>{if(!confirm("Stop cloud pairing? Queued posts will still wait for the local browser runner."))return;const r=await fetch("/api/automation/browser",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"disable"})});if(r.ok)await refresh();else setError("Could not stop cloud pairing.");}}>Stop cloud pairing</button>}</div><p className="auto-muted">Browser posting and profile sync run only when you press a browser button. Use Open secure Edge sign-in when adding another Gmail; finish Google sign-in in Edge, close that Edge window, then sync that account from Accounts.</p>{!manual&&<p className="auto-note">The local browser runner is not open. Start “GMB AutoPilot Manual Button Server” on this computer, then click Check connection.</p>}{status?.lastSeenAt&&<p className="auto-muted">Cloud contact: {new Date(status.lastSeenAt).toLocaleString()}</p>}{manual?.lastRun&&<p className="auto-muted">Last browser run: {new Date(manual.lastRun.finishedAt).toLocaleString()} · exit code {manual.lastRun.code}</p>}{error&&<p role="alert" className="auto-error-text">{error}</p>}<p className="auto-muted">Profile discovery and post publishing are browser automated. Advanced profile creation drafts are saved here, then completed in Google Business Profile.</p></section>;
}
